apiVersion: apps/v1
kind: Deployment
metadata:
  name: pyapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pyapp1
  template:
    metadata:
      labels:
        app: pyapp1
    spec:
      containers:
      - name: pyapp1
        ports:
        - containerPort: 8090