apiVersion: apps/v1
kind: Deployment
metadata:
  name: pyapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pyapp1
  template:
    metadata:
      labels:
        app: pyapp1
    spec:
      containers:
      - name: pyapp1
        image: 982210731409.dkr.ecr.us-east-2.amazonaws.com/pyapp
        ports:
        - containerPort: 8090
        resources:
          requests:
            memory: "500Mi"
            cpu: "250m"
          limits:
            memory: "500Mi"
            cpu: "250m"